default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: agiledata
  encoding: unicode
  pool: 5

test:
  <<: *default
  database: db/test.sqlite3
