project = Project.create!(name: 'Agile project, LOL')
project.tasks << Task.new(start_date: 15.days.ago, end_date: 10.days.ago)
project.tasks << Task.new(start_date: 12.days.ago, end_date: 8.days.ago)
project.tasks << Task.new(start_date: 10.days.ago, end_date: 3.days.ago)
project.tasks << Task.new(start_date: 5.days.ago)
project.tasks << Task.new(start_date: 2.days.ago)